# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Estonian (Tartu Ülikool spellchecker (Tartu Ülikool"
et = "Autonym spellchecker (Tartu Ülikool"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Estonian (Tartu Ülikool, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
et = "TRANSLATE: A spellchecker for Estonian (Tartu Ülikool, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.et"

[windows]
system_product_code = "{E6D875B4-0A1D-4945-8AC2-7C218C836971}_is1"
legacy_product_codes = [
    { value = "87990427-23D7-4340-96AE-451B1BF37140", kind = "nsis" },
    { value = "6621ACB5-4262-429D-90B0-C791897BD662", kind = "nsis" }
]

[package.speller]
name = "Estonian (Tartu Ülikool"
version = "0.1.1"

[package.grammar]
name = "Estonian (Tartu Ülikool"
version = "0.1.0"

[package.tts-textproc]
name = "Estonian (Tartu Ülikool"
version = "0.1.0"

[package.hyphenator]
name = "Estonian"
version = "0.1.0"
