template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "esto1258"
__REPO__ = "lang-est-x-utee"
__UND2C__ = "et"
__UNDEFINED__ = "Estonian"
__UND__ = "est"
